export interface Lesson {
  no: number; title: string; seconds: number | null; altSeconds?: number; goal: string; exercise: string; prompt: string;
}

const MORNING = "Morning check for [SYMBOL]: higher-timeframe trend, nearest key zones, any setup matching my rules (no trade is a valid answer), and remind me to check the economic calendar.";

export const LESSONS: Lesson[] = [
  { no: 1, title: "What AI trading is & what AI can and can't do", seconds: 324, altSeconds: 552, goal: "Realistic expectations.", exercise: "Write 3 things AI can help you with and 3 things it cannot do for you.", prompt: MORNING },
  { no: 2, title: "Connect Claude to TradingView (MCP setup)", seconds: 706, goal: "Install the TradingView MCP (github.com/tradesdontlie/tradingview-mcp) with Claude Code + TradingView Desktop; test with tv_health_check.", exercise: "Install the MCP and run the health check until it reports your symbol and price.", prompt: "Use tv_health_check to verify TradingView is connected. Then tell me the symbol, timeframe and current price you can see." },
  { no: 3, title: "Prompting Claude with a live chart", seconds: 1182, goal: "One task at a time, share your view first.", exercise: "Ask Claude to explain one chart without giving a trade idea.", prompt: "I'm a beginner. Explain what this [SYMBOL] [TIMEFRAME] chart is showing in plain language. Don't give me a trade idea." },
  { no: 4, title: "Market structure (swing highs/lows, BOS, CHoCH)", seconds: 1346, goal: "Read trend from structure.", exercise: "Mark swing points on one chart yourself, then compare with Claude.", prompt: "My view: I think [SYMBOL] on the [TIMEFRAME] is in a [UPTREND/DOWNTREND/RANGE] because [REASON]. Do you agree? Mark the major swing highs and lows from [DATE], define what you count as a swing point, point out any BOS or CHoCH, and tell me where my reasoning is wrong." },
  { no: 5, title: "Support & resistance zones", seconds: 1650, goal: "Zones, not lines; verify yourself.", exercise: "Add 3 key levels to a watchlist symbol and verify each on the chart.", prompt: "Find the 3 to 5 most significant support and resistance ZONES since [DATE]. Draw zones, not lines. For each, give the reason and number of touches." },
  { no: 6, title: "Indicators (SMA, MACD, RSI) & confluence", seconds: 2050, goal: "Look for agreement between signals.", exercise: "List agreeing and disagreeing signals on one chart.", prompt: "List every signal on this chart that points in the same direction right now, then list the signals that disagree. Be honest if there is little confluence." },
  { no: 7, title: "Multi-timeframe analysis", seconds: 2510, goal: "Higher TF bias, lower TF entry.", exercise: "Pick your bias timeframe and entry timeframe and write them in your plan.", prompt: "Analyse [SYMBOL] on the [HIGHER TF] for bias and the [LOWER TF] for entries. Ask me questions first if unclear. Keep it short." },
  { no: 8, title: "Building a rules-based strategy", seconds: 2863, goal: "Write the Trading Plan tab.", exercise: "Fill in every section of your Trading Plan.", prompt: "Help me turn this idea into exact, testable rules: [IDEA]. Write entry, stop, target and when NOT to trade. Point out anything vague." },
  { no: 9, title: "Backtesting", seconds: 3186, goal: "Always compare to buy-and-hold, include fees and slippage, test on other assets and periods.", exercise: "Backtest your rules on 2 assets and 2 periods; note the results.", prompt: "Backtest these exact rules in TradingView's Strategy Tester with realistic commissions and slippage. Compare to buy-and-hold. Report trades, win rate, average R, profit factor, max drawdown, and how much profit came from the top 3 trades." },
  { no: 10, title: "Risk management & position sizing", seconds: 3683, goal: "Size every trade from your stop.", exercise: "Calculate size for 3 example trades using the ticket.", prompt: "Entry [X], stop [Y], target [Z], account R[AMOUNT], risk 1%. Calculate position size and risk-to-reward, and check the stop is at a logical level." },
  { no: 11, title: "Paper trading phase", seconds: null, goal: "30 trades under the written plan.", exercise: "Log and review 30 paper trades in the Paper Trade tab.", prompt: "Review my trade: setup, entry/stop/target, risk %, R result, rule followed Y/N. Was this a good trade or just a good outcome?" },
  { no: 12, title: "Live trading with small size + daily routine + using AI safely", seconds: 3940, goal: "Small size, same rules, daily routine.", exercise: "Write your daily routine in the plan and follow it for a week.", prompt: MORNING },
];
