import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

interface GatewayRequest {
  messages: Array<{ role: string; content: string }>;
  tools?: any[];
  tool_choice?: any;
  model?: string;
  preference?: "fastest" | "quality"; // user preference for fallback order
}

interface ProviderConfig {
  name: string;
  url: string;
  getHeaders: () => Record<string, string>;
  getModel: (requestedModel?: string) => string;
}

function getProviders(preference: "fastest" | "quality" = "fastest"): ProviderConfig[] {
  const lovable: ProviderConfig = {
    name: "lovable",
    url: "https://ai.gateway.lovable.dev/v1/chat/completions",
    getHeaders: () => ({
      Authorization: `Bearer ${Deno.env.get("LOVABLE_API_KEY")}`,
      "Content-Type": "application/json",
    }),
    getModel: (m) => m || "google/gemini-3-flash-preview",
  };

  const gemini: ProviderConfig = {
    name: "gemini",
    url: "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions",
    getHeaders: () => ({
      Authorization: `Bearer ${Deno.env.get("GEMINI_API_KEY")}`,
      "Content-Type": "application/json",
    }),
    getModel: () => "gemini-2.5-flash",
  };

  const openai: ProviderConfig = {
    name: "openai",
    url: "https://api.openai.com/v1/chat/completions",
    getHeaders: () => ({
      Authorization: `Bearer ${Deno.env.get("OPENAI_API_KEY")}`,
      "Content-Type": "application/json",
    }),
    getModel: () => "gpt-4o-mini",
  };

  // Primary is always Lovable
  if (preference === "quality") {
    return [lovable, openai, gemini];
  }
  return [lovable, gemini, openai];
}

async function tryProvider(
  provider: ProviderConfig,
  body: GatewayRequest,
  timeoutMs = 30000,
): Promise<{ ok: boolean; data?: any; status?: number; provider: string }> {
  // Check if key is configured
  try {
    const headers = provider.getHeaders();
    if (!headers.Authorization || headers.Authorization === "Bearer " || headers.Authorization === "Bearer undefined" || headers.Authorization === "Bearer null") {
      return { ok: false, status: 0, provider: provider.name };
    }
  } catch {
    return { ok: false, status: 0, provider: provider.name };
  }

  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), timeoutMs);

    const requestBody: any = {
      model: provider.getModel(body.model),
      messages: body.messages,
    };
    if (body.tools) requestBody.tools = body.tools;
    if (body.tool_choice) requestBody.tool_choice = body.tool_choice;

    const res = await fetch(provider.url, {
      method: "POST",
      headers: provider.getHeaders(),
      body: JSON.stringify(requestBody),
      signal: controller.signal,
    });

    clearTimeout(timer);

    if (!res.ok) {
      const status = res.status;
      console.error(`[ai-gateway] ${provider.name} failed: ${status}`);
      try { await res.text(); } catch {}
      return { ok: false, status, provider: provider.name };
    }

    const data = await res.json();
    return { ok: true, data, provider: provider.name };
  } catch (e) {
    console.error(`[ai-gateway] ${provider.name} error:`, e);
    return { ok: false, status: 0, provider: provider.name };
  }
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const body = (await req.json()) as GatewayRequest;
    const preference = body.preference ?? "fastest";
    const providers = getProviders(preference);

    let lastStatus = 0;

    for (const provider of providers) {
      const result = await tryProvider(provider, body);
      if (result.ok) {
        // Extract tool call result if present
        const toolCall = result.data?.choices?.[0]?.message?.tool_calls?.[0];
        let parsed: any = null;
        if (toolCall) {
          try { parsed = JSON.parse(toolCall.function.arguments); } catch {}
        }

        return new Response(JSON.stringify({
          result: parsed ?? result.data?.choices?.[0]?.message?.content ?? null,
          raw: result.data,
          ai_status: "ok",
          provider_used: result.provider,
          message: `Generated by ${result.provider}`,
        }), {
          status: 200,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      lastStatus = result.status ?? 0;
    }

    // All providers failed
    const aiStatus = lastStatus === 429 ? "rate_limited" : lastStatus === 402 ? "degraded" : "error";
    const message = lastStatus === 429 ? "All AI providers rate limited" : lastStatus === 402 ? "AI credits exhausted" : "All AI providers unavailable";

    return new Response(JSON.stringify({
      result: null,
      ai_status: aiStatus,
      provider_used: "none",
      message,
    }), {
      status: 200,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("[ai-gateway] error:", e);
    return new Response(JSON.stringify({
      result: null,
      ai_status: "error",
      provider_used: "none",
      message: String(e),
    }), {
      status: 200,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
